import { Contrato } from './contrato.model'

export interface ContaLuz{
  bandeiraTarifaria: 0,
  bandeiraTarifariaValorCOFINS: 0,
  bandeiraTarifariaValorFornecido: 0,
  bandeiraTarifariaValorICMS: 0,
  bandeiraTarifariaValorPIS: 0,
  bandeiraTarifariaValorValorTotal: 0,
  cipConsumoValorCOFINS: 0,
  cipConsumoValorICMS: 0,
  cipConsumoValorPIS: 0,
  cipConsumoValorTotal: 0,
  cipValorFornecido: 0,
  cofinsValor: 0,
  consumoMes: 0,
  data_luz: string,
  icmsvalor: 0,
  id_conta_luz: 0,
  instalacao_luz_fk: 0,
  periodo_luz: string,
  pisValor: 0,
  teConsumoValorCOFINS: 0,
  teConsumoValorFornecido: 0,
  teConsumoValorICMS: 0,
  teConsumoValorPIS: 0,
  teConsumoValorTotal: 0,
  tusdConsumoValorCOFINS: 0,
  tusdConsumoValorFornecido: 0,
  tusdConsumoValorICMS: 0,
  tusdConsumoValorPIS: 0,
  tusdConsumoValorTotal: 0
}
